countries_not_in_pycountry_converter = {
    "Virgin Islands British": "North America",
    "Myanmar (Burma)": "Asia",
    "Antigua And Barbuda": "North America",
    "Saint Helena": "Africa",
    "Timor-Leste (East Timor)": "Asia",
    "Bosnia And Herzegovina": "Europe",
    "Saint Kitts And Nevis": "North America",
    "Democratic Republic Of The Congo": "Africa",
    "Saint Vincent And The Grenadines": "North America",
    "Antarctica": "Antarctica",
    "Wallis And Futuna": "Oceania",
    "Turks And Caicos Islands": "North America",
    "Isle Of Man": "Europe",
    "Trinidad And Tobago": "North America",
    "Sao Tome And Principe": "Africa",
    "Kosovo": "Europe",
    "Reunion": "Africa",
    "Saint Pierre And Miquelon": "North America",
    "Virgin Islands Us": "North America",
    "United States Minor Outlying Islands": "North America",
    "Western Sahara": "Africa",
    "South Georgia And The South Sandwich Islands": "Antarctica",
    "Saint Barthelemy": "North America",
    "Saint Martin": "North America",
    "Sint Maarten": "North America",
    "Palestinian Territory": "Asia",
    "French Southern Territories": "Antarctica",
    "Heard Island And Mcdonald Islands": "Antarctica",
    "Cocos Islands": "Asia",
    "Curacao": "North America",
    "Cape Verde": "Africa",
    "Caribbean Netherlands": "North America",
    "British Indian Ocean Territory": "Asia",
    "Bonaire Sint Eustatius And Saba": "North America",
    "Bouvet Island": "Antarctica",
    "American Samoa": "Oceania",
    "Anguilla": "North America",
    "Aruba": "North America",
    "Bermuda": "North America",
    "Bhutan": "Asia",
    "Cayman Islands": "North America",
    "Christmas Island": "Asia",
    "Cocos Keeling Islands": "Asia",
    "Cook Islands": "Oceania",
    "Falkland Islands": "South America",
    "Faroe Islands": "Europe",
    "French Polynesia": "Oceania",
    "French Guiana": "South America",
    "Gibraltar": "Europe",
    "Greenland": "North America",
    "Guadeloupe": "North America",
    "Guam": "Oceania",
    "Guernsey": "Europe",
    "Hong Kong": "Asia",
}
